### ISSUE TITLE
only the first test form test suite is added to xml report

### ISSUE THREAD

**Issue by mikhail-angelov** [gemini-testing/hermione-allure-reporter#19]
I've tried the lates version of hermione and hermione-allure-reporter, and faced with issue
if I have several tests in description, 
like this
```
describe('suite 1', function(){

it('test1', function(){})

it('test2', function(){})

})
```

only first (`'test1'`) is added to xml report

**Comment by ashchogoleva** [comment]
@j0tunn @eGavr 
Hey, guys. Any news about this issue?

**Comment by DudaGod** [comment]
Hi. We have already fixed it in hermione. Use latest version - [0.56.0](https://github.com/gemini-testing/hermione/tree/v0.56.0).
