### ISSUE TITLE
Not supported "enabled" config param

### ISSUE THREAD

**Issue by dicrtarasov** [gemini-testing/hermione-allure-reporter#25]
```
        'allure-hermione': {
            resultsDir: './allure-results',
            enabled: false
        },
```

does not turn plugin off

version: allure-hermione@2.7.0

**Comment by DudaGod** [comment]
Hello.

This package has not been supported for a long time. In about section you can see text like: 💀💀💀[DEPRECATED]💀💀💀 use this plugin instead – https://github.com/gemini-testing/html-reporter.

If for some reason html-reporter plugin does not suit you, then you can use [allure-hermione](https://github.com/allure-framework/allure-js/tree/main/packages/allure-hermione), which is supported by allure maintainers.
